// <auto-generated />
namespace JumpChain.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removedJumpList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedJumpList));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091440011_removedJumpList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
